---
apiVersion: v1
kind: Pod
metadata:
  name: testenv
  labels:
    app: website
spec:
  containers:
  - name: website
    image: remigiuszdonczyk/final-project:latest
#    volumeMounts:
#    - mountPath: /var/lib/mysql
#      name: persistent-db
#  volumes:
#  - name: persistent-db
#    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: testenv-deploy
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

