name: CI

on:
  pull_request:
    branches: [ "prod" ]
    types: [opened, edited, synchronize, reopened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: pr-
          prefix_case_sensitive: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
